//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forfattare
    {
        public Forfattare()
        {
            this.Boks = new HashSet<Bok>();
        }
    
        public int ForfattarId { get; set; }
        public string ForNamn { get; set; }
        public string EfterNamn { get; set; }
        public string FodelseAr { get; set; }
        public Nullable<System.DateTime> AvlidenAr { get; set; }
        public string Sprak { get; set; }
        public string Land { get; set; }
    
        public virtual ICollection<Bok> Boks { get; set; }
    }
}
