//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kund
    {
        public Kund()
        {
            this.Lans = new HashSet<Lan>();
        }
    
        public int KundId { get; set; }
        public string ForNamn { get; set; }
        public string EfterNamn { get; set; }
        public string Adress { get; set; }
        public string HemTelefon { get; set; }
        public string MobilTelefon { get; set; }
        public string Epost { get; set; }
        public string Kon { get; set; }
        public string FodelseAr { get; set; }
    
        public virtual ICollection<Lan> Lans { get; set; }
    }
}
