//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotek
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAntalKopiorTillgangligaUtlaning
    {
        public string Titel { get; set; }
        public Nullable<int> AntalTillgangliga { get; set; }
    }
}
